version: '3'
services:
  db:
    image: mysql
    container_name: my-mysql
    environment:
      MYSQL_DATABASE: doublevpartners_prueba
      MYSQL_USER: root
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3308"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
